on:
  - push
  - pull_request

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: make unit-test
